GET http://localhost:3000/test-get

###

POST http://localhost:3000/test-post
Content-Type: application/json
# Content-Type: text/plain

{
  "id": "{{$guid}}",
  "name": "POST Payload",
  "description": "This is just a test payload!",
  "createdAt": "{{$timestamp}}"
}

###

PUT http://localhost:3000/test-put
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "PUT Payload",
  "description": "This is just a test payload!",
  "createdAt": "{{$timestamp}}"
}

###

POST http://localhost:3000/hacky
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "Hacky Payload",
  "description": "This is just a test payload!",
  "createdAt": "{{$timestamp}}"
}

###

POST http://localhost:3000/works
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "Plain Handler Payload",
  "description": "This is just a test payload!",
  "createdAt": "{{$timestamp}}"
}